_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-x86_64
data:
    value: data/Question.xlsx
model:
    value: svm
save_path:
    value: api/models/
